# Generated by Django 4.0.4 on 2022-07-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
