# Generated by Django 4.0.4 on 2022-07-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labfacility',
            name='image_caption',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labfacility',
            name='image_heading',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
