# Generated by Django 4.0.4 on 2022-07-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0002_labfacility_image_caption_labfacility_image_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labfacility',
            name='image_caption',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labfacility',
            name='image_heading',
            field=models.TextField(max_length=100),
        ),
    ]
