# Generated by Django 4.0.4 on 2022-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0003_alter_labfacility_image_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='computing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computing_heading', models.TextField(max_length=100)),
                ('computing_url', models.TextField(max_length=100, null=True)),
                ('computing_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
