# Generated by Django 4.0.4 on 2022-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0005_computing_computing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computing',
            name='computing_url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
