# Generated by Django 4.0.4 on 2022-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0006_alter_computing_computing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='labfacility',
            name='lab_sections',
            field=models.TextField(choices=[('Classrooms', 'Classrooms'), ('Labs Equipment', 'Labs Equipment'), ('Instruments', 'Instruments')], default='Demo'),
            preserve_default=False,
        ),
    ]
