# Generated by Django 4.0.4 on 2022-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceApp', '0007_labfacility_lab_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(max_length=100)),
                ('service_description', models.TextField(blank=True, max_length=100, null=True)),
                ('service_link', models.TextField(max_length=100)),
                ('service_cover', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
