# Generated by Django 4.0.4 on 2022-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=100)),
                ('about', models.TextField(max_length=500, null=True)),
                ('url', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.TextField(max_length=100)),
            ],
        ),
    ]
