# Generated by Django 4.0.4 on 2022-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('email', models.EmailField(max_length=50)),
                ('student_type', models.TextField(choices=[('Graduate', 'Graduate'), ('Undergrad', 'Undergrad')])),
            ],
        ),
    ]
