# Generated by Django 4.0.4 on 2022-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleApp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(default='The demo thing', max_length=100),
            preserve_default=False,
        ),
    ]
