# Generated by Django 4.0.4 on 2022-07-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_by_direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_fields', models.TextField(choices=[('Sustainability Energy', 'Sustainability Energy'), ('Medicel', 'Medicel')])),
                ('project_name', models.CharField(max_length=250)),
                ('project_category', models.CharField(max_length=250)),
                ('project_date', models.DateField()),
                ('project_link', models.CharField(max_length=250)),
                ('project_description', models.TextField(max_length=250)),
                ('research_cover_1', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('research_cover_2', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
