# Generated by Django 4.0.4 on 2022-07-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchApp', '0002_research_by_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_by_direction',
            name='research_cover_3',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
