# Generated by Django 4.0.4 on 2022-08-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peopleApp', '0002_student'),
        ('researchApp', '0004_alter_research_by_direction_research_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sustainability', models.TextField(max_length=250)),
                ('Energy', models.TextField(max_length=250)),
                ('Artificial_Intelligence', models.TextField(max_length=250)),
                ('Education', models.TextField(max_length=250)),
                ('facutly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peopleApp.faculty')),
            ],
        ),
        migrations.DeleteModel(
            name='research_by_area',
        ),
    ]
