# Generated by Django 4.0.4 on 2022-08-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchApp', '0006_research_by_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_overview',
            old_name='facutly',
            new_name='overview_facutly',
        ),
    ]
