# Generated by Django 4.0.4 on 2022-08-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchApp', '0007_rename_facutly_research_overview_overview_facutly'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_overview',
            name='Biomedical',
            field=models.TextField(default='www.google.com', max_length=250),
            preserve_default=False,
        ),
    ]
