# Generated by Django 4.0.4 on 2022-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchApp', '0008_research_overview_biomedical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_overview',
            name='Artificial_Intelligence',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='research_overview',
            name='Biomedical',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='research_overview',
            name='Education',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='research_overview',
            name='Energy',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='research_overview',
            name='Sustainability',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
