# Generated by Django 4.0.4 on 2022-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistryAdmin', '0002_research_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='research',
        ),
    ]
