# Generated by Django 4.0.4 on 2022-08-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0002_seminer_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminer',
            name='seminer_notes',
            field=models.TextField(default='Hello honey bunny', max_length=500),
            preserve_default=False,
        ),
    ]
