# Generated by Django 4.0.4 on 2022-09-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0004_courseannouncemets'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncemets',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
