# Generated by Django 4.0.4 on 2022-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_faculty_faculty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='url',
            field=models.TextField(default='#', max_length=100),
            preserve_default=False,
        ),
    ]
