# Generated by Django 4.0.4 on 2022-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_faculty_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.TextField(max_length=100)),
            ],
        ),
    ]
