# Generated by Django 4.0.4 on 2022-07-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='publication_video',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_title',
            field=models.CharField(max_length=100),
        ),
    ]
