# Generated by Django 4.0.4 on 2022-07-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='research_by_area',
        ),
    ]
