# Generated by Django 4.0.4 on 2022-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_delete_research_by_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.TextField(max_length=100)),
                ('banner_description', models.TextField(max_length=100)),
                ('banner_url', models.TextField(max_length=100)),
                ('banner_cover', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
    ]
