# Generated by Django 4.0.4 on 2022-08-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(max_length=100)),
                ('news_cover', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('news_description', models.TextField(max_length=100)),
                ('news_category', models.TextField(max_length=100)),
                ('news_url', models.TextField(max_length=100)),
            ],
        ),
    ]
