# Generated by Django 4.0.4 on 2022-08-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='featured',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
